name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Run pwd
        run: pwd
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 11
          distribution: zulu
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Test with Gradle
        run: ./gradlew --info test
