name: CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      
      - name: Run ls -al
        run: ls -al
      
      - name: Set up JDK 11
        uses: actions/setup-java@v3.4.1
        with:
          java-version: 11
          distribution: zulu
      
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build without Test
        run: ./gradlew clean build -x test

      - name: Test with Gradle
        run: ./gradlew --info test
      
      - name: Notify failure
        uses: 8398a7/action-slack@v3.12.0
        env:
          SLACK_WEBHOOK_URL: https://hooks.slack.com/services/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
        with:
          status: ${{ job.status }}
          username: incoming-webhook
          channel: '#failure'
        if:
          failure()
          
